### ISSUE TITLE
Can't post Bun sticker in #bun

### ISSUE THREAD

**Issue by heimskr** [xhyrom/bun-discord-bot#39]
If you post the `bun` sticker by itself in `#bun` without including "bun" or a Bun emoji, the message will be deleted. Ideally, the sticker by itself should count.

**Comment by heimskr** [comment]
i am suffering greatly as a result of this bug, pls fix

**Comment by xhyrom** [comment]
thanks for reporting, I'll fix this tomorrow. Gonna sleep now :D

**Comment by heimskr** [comment]
thank
